Repository TheThingsNetwork/docs, pull requests merged in 2020-11, with the labels that each got.

#393 Add multitech basics station guide
  _content/gateways/basics-station/index.md
  _content/gateways/certificates/index.md
  _content/gateways/multitech/aep.md
  _content/gateways/multitech/index.md
  _content/gateways/multitech/lbs-menu.png
  _content/gateways/multitech/lbs-save.png
  _content/gateways/multitech/lora-settings-1.png
  _content/gateways/multitech/lora-settings-2.png
  _content/gateways/multitech/putty-aep.png
  _content/gateways/multitech/putty-warning.png
  _content/gateways/multitech/save-and-apply.png
  _content/gateways/multitech/wget.png
Labels: blocked, doc

#402 Add MacOS Ruby note
  README.md
Labels: doc

#411 fix broken link to v3 stack documentation
  index.html
Labels: bug, easy
